### ISSUE TITLE
Missing modules in Win10

### ISSUE THREAD

**Issue by jumpjack** [Kawaboongawa/Zolver#12]
PyQT5
scikit-image
sklearn

**Comment by simin75simin** [comment]
i got it to work on win10 all right. i removed the version info in requirements.txt so my requirements.txt looks like this:

```
numpy
scipy
opencv_python<3.5
scikit_image
matplotlib
Pillow
PyQt5
scikit_learn
```
the only thing i needed changing is opencv_python<3.5 cause its version is too old. 
windows 10 family edition here with python3.7.9

**Comment by Chenfyuan42** [comment]
> i got it to work on win10 all right. i removed the version info in requirements.txt so my requirements.txt looks like this:
> 
> ```
> numpy
> scipy
> opencv_python<3.5
> scikit_image
> matplotlib
> Pillow
> PyQt5
> scikit_learn
> ```
> 
> the only thing i needed changing is opencv_python<3.5 cause its version is too old. windows 10 family edition here with python3.7.9

Hi, I am also trying to run this project on Win10 and thanks to your tips I solved some minor problems. But I am having the problem as shown in the picture. I would like to ask if it is a problem with the file directory in the code or some other part that needs to be changed? Thank you very much for your help and I wish you a happy new year.
![1672695628247](https://user-images.githubusercontent.com/72538611/210279695-59611d91-322b-49e7-ba42-6b901ab33e45.png)

**Comment by Chenfyuan42** [comment]
> i got it to work on win10 all right. i removed the version info in requirements.txt so my requirements.txt looks like this:
> 
> ```
> numpy
> scipy
> opencv_python<3.5
> scikit_image
> matplotlib
> Pillow
> PyQt5
> scikit_learn
> ```
> 
> the only thing i needed changing is opencv_python<3.5 cause its version is too old. windows 10 family edition here with python3.7.9
I'm sorry to bother you again, but after I changed the directory to an absolute path to my computer, the problem described earlier was solved. However, my program window displays a grayscale image for a moment and then flashes back. Have you encountered a similar problem?

**Comment by lhgl** [comment]
> > i got it to work on win10 all right. i removed the version info in requirements.txt so my requirements.txt looks like this:
> > ```
> > numpy
> > scipy
> > opencv_python<3.5
> > scikit_image
> > matplotlib
> > Pillow
> > PyQt5
> > scikit_learn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the only thing i needed changing is opencv_python<3.5 cause its version is too old. windows 10 family edition here with python3.7.9
> 
> Hi, I am also trying to run this project on Win10 and thanks to your tips I solved some minor problems. But I am having the problem as shown in the picture. I would like to ask if it is a problem with the file directory in the code or some other part that needs to be changed? Thank you very much for your help and I wish you a happy new year. ![1672695628247](https://user-images.githubusercontent.com/72538611/210279695-59611d91-322b-49e7-ba42-6b901ab33e45.png)

I resolved this,  adding absolute path, and changing the '/' to '\\' in Windows. 

Like :

`self.absolut_path = str(pathlib.Path().absolute())
cv2.imwrite(self.absolut_path  + "\\tmp\\resized.png", self.img)`

**Comment by FizzyMUC** [comment]
Thanks! At least I could install the packages. I still get this error

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/pascal/.local/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

```
